"""
Django settings for django_blog project.

Generated by 'django-admin startproject' using Django 6.0.2.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
SECRET_KEY = 'django-insecure-fp(=o05-tv(fs=ag2j#ef^(jfairt_4)l+k1)j*^3k$j7g7jy$'
DEBUG = True
ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',  # 已正确添加博客应用
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_blog.wsgi.application'


# Database - 修正MySQL配置（解决中文乱码+适配Django 6.0）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'python_blog',  # 需确保MySQL中已创建该数据库
        'USER': 'root',
        'PASSWORD': '123456',  # 你的MySQL密码
        'HOST': '127.0.0.1',
        'PORT': '3306',
        # 新增：解决中文乱码+兼容MySQL 8.0
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation - 临时放宽密码规则（适配你的123456密码）
AUTH_PASSWORD_VALIDATORS = [
    # 注释掉纯数字验证器（否则123456密码无法创建用户）
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    # 临时放宽密码长度（否则123456太短）
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 6,  # 默认8，改为6适配123456
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
]


# Internationalization - 修正为中文+北京时间
LANGUAGE_CODE = 'zh-hans'  # 中文
TIME_ZONE = 'Asia/Shanghai'  # 北京时间
USE_I18N = True
USE_TZ = True  # 保持True，Django会自动转换时区


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# 媒体文件配置（用户上传的文章图片）- 统一Path写法，避免路径错误
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'  # 替换os.path，用Path对象更规范

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'